version: "3.8"
services:
  consul:
    image: 'consul:1.8'
    ports:
      - '8500:8500'
      - '8600:8600/udp'

  redis:
    image: 'redis:5-alpine'
    ports:
      - '6379:6379'

  boss:
    #    build: ./boss
    image: boss
    environment:
      CONSUL_ADDR: 'consul:8500'
      GIN_MODE: 'release'
    ports:
      - '8081:8081'
    depends_on:
      - consul

  head42:
    image: 'head'
    ports:
      - '8080'
    environment:
      CONSUL_ADDR: 'consul:8500'
      REDIS_ADDR: 'redis:6379'
      INSTANCE: head-42
      FAKE_STEPPER: "1"

  head43:
    image: 'head'
    ports:
      - '8080'
    environment:
      CONSUL_ADDR: 'consul:8500'
      REDIS_ADDR: 'redis:6379'
      INSTANCE: head-43
      FAKE_STEPPER: "1"

  camera01:
    image: camera
    environment:
      INSTANCE: camera-01
      FILENAME: /d/pi42.raw
      DRAW_FRAME: resized
      MOTION_DETECT_WIDTH: 320
      MOTION_THRESHOLD: 4
    volumes:
      - ./dev:/d:ro
    ports:
      - 5010:5000

  camera02:
    image: camera
    environment:
      INSTANCE: camera-02
      FILENAME: /d/pi43.raw
    volumes:
      - ./dev:/d:ro
    ports:
      - 5011:5000




