FROM golang:1.15-buster@sha256:29452ef08bd0535f550c47b6034522c82ac10517b49c5f3b7a00035ecee0089e

WORKDIR /pkg

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget dpkg-dev

RUN arch=`dpkg-architecture -q DEB_BUILD_ARCH`; \
    wget https://theheads.sfo2.digitaloceanspaces.com/build/opencv_4.4.0-2_${arch}.deb

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ./opencv_4.4.0-2_*.deb
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg

COPY camera/go.* /build/camera/
COPY common/go.* /build/common/

WORKDIR /build/camera/
RUN go mod download

COPY camera /build/camera
COPY common /build/common

RUN CGO_ENABLED=1 go build ./cmd/camera

WORKDIR /app
RUN cp /build/camera/camera /build/camera/index.html .
RUN cp -r /build/camera/js js

CMD ["./camera"]
