name: dev
stands:
- cameras:
  - description: Raspberry Pi PiNoir Camera V2 Video Module
    fov: 64.33
    name: camera0
    pos: {x: 0.1, y: 0}
    rot: 0
  heads:
  - name: vhead-00
    pos: {x: 0, y: 0}
    rot: 0
  name: stand0
  pos: {x: -0.75, y: 0}
  rot: -90
- cameras:
  - description: Raspberry Pi PiNoir Camera V2 Video Module
    fov: 64.33
    name: camera1
    pos: {x: 0.1, y: 0}
    rot: 0
  heads:
  - name: vhead-01
    pos: {x: 0, y: 0}
    rot: 0
  name: stand1
  pos: {x: 0.75, y: 0}
  rot: -90
- cameras:
  - description: Mac built-in
    fov: 60
    name: camera2
    pos: {x: 0, y: 0}
    rot: 0
  enabled: true
  heads: []
  name: stand2
  pos: {x: 0, y: 0}
  rot: -90
