FROM golang:1.14-buster

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build .

WORKDIR /app
RUN cp /build/raftsync .

ARG VERSION
RUN mkdir -p /packages
RUN tar -czvf /packages/raftsync_${VERSION}_armhf.tar.gz app

RUN curl -XPUT \
    http://raftsync.service.consul:9000/theheads/build/raftsync_${VERSION}_armhf.tar.gz \
    --data-binary @/packages/raftsync_${VERSION}_armhf.tar.gz

WORKDIR /app

CMD ["./raftsync"]