FROM python:3.7-buster AS build-env
WORKDIR /app

COPY requirements.txt .
RUN pip install -r ./requirements.txt

COPY *.py ./

RUN pip install pyinstaller
RUN pyinstaller head.py

FROM python:3.7-buster AS run

COPY --from=build-env /app/dist/head /app/head

CMD ["/app/head/head"]