FROM heads-build-arm64

WORKDIR /build

COPY common ./common
COPY leds ./leds
COPY cmd/leds ./cmd/leds
COPY Makefile .

RUN make bin/leds
RUN mkdir app
RUN cp bin/leds app

RUN tar -czvf "leds_0.0.0_arm64.tar.gz" app