FROM golang:1.17-buster@sha256:74ba26bff6b9335172e4a84c6bb69a6fd3876c9d06ce7839ff7cc14637893f9d

WORKDIR /pkg

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget dpkg-dev

RUN arch=`dpkg-architecture -q DEB_BUILD_ARCH`; \
    wget https://theheads.sfo2.digitaloceanspaces.com/build/opencv_4.4.0-2_${arch}.deb

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ./opencv_4.4.0-2_*.deb
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY common common

COPY camera camera
COPY cmd/camera ./cmd/camera
RUN go build -o `mktemp -d` ./cmd/camera

