FROM debian:buster@sha256:9740683722a2a8aa497a5b23e4bc229fcf8b8991e26d3935540c7704ff24012e AS lib_builder

WORKDIR /foundry

RUN apt-get update -y && apt-get install -y build-essential cmake git

RUN git clone https://github.com/jgarff/rpi_ws281x.git \
  && cd rpi_ws281x \
  && mkdir build \
  && cd build \
  && cmake -D BUILD_SHARED=OFF -D BUILD_TEST=OFF .. \
  && cmake --build . \
  && make install

FROM golang:1.17-buster@sha256:906bbd99aa4b9349744f7b24057b196370f2daf3b048cad8ea4f7a8084ace2a5

COPY --from=lib_builder /usr/local/lib/libws2811.a /usr/local/lib/
COPY --from=lib_builder /usr/local/include/ws2811 /usr/local/include/ws2811

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY common common

COPY leds leds
COPY cmd/leds ./cmd/leds
RUN go build -o `mktemp -d` ./cmd/leds

COPY cmd/lowred ./cmd/lowred
RUN go build -o `mktemp -d` ./cmd/lowred