FROM heads-build-arm64

WORKDIR /build

COPY common ./common
COPY boss ./boss

RUN cd boss && CGO_ENABLED=1 go build ./cmd/boss

RUN mkdir app
RUN cp boss/boss boss/boss.html app
COPY --from=boss-ui /install app/boss-ui/build
RUN tar -czvf "boss_0.0.0_arm64.tar.gz" app