{
 "title": "System Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "rtunneld active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rtunneld_active_connections)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "services that are down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - up{job!=\"camera\"}) > 0",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "has leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "journald_logged_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(journald_logged_total[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jsu_rpi_cpu_temp_degrees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi_cpu_temp_degrees", "legendFormat": "{{instance}} {{zone}}" }
   ]
  },
  {
   "title": "Load5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "rtunneld_listener_start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rtunneld_listener_start[2m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "rtunneld_healthy_tunnels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rtunneld_healthy_tunnels)", "legendFormat": "sum" }
   ]
  },
  {
   "title": "rtunneld_healthcheck_failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rtunneld_healthcheck_failures[2m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_boot_time_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_boot_time_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_wifi_station_signal_dbm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_wifi_station_signal_dbm[40s])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2, go_memstats_alloc_bytes)",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",job=\"node-exporter\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Receive bps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"wlan0\",job!=\"wireless_router\"}[30s])*8"
    }
   ]
  },
  {
   "title": "prometheus_notifications_alertmanagers_discovered",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered"
    }
   ]
  },
  {
   "title": "Heads Camera FPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heads_camera_frame_processed[10s])"
    }
   ]
  },
  {
   "title": "Transmit bps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"wlan0\", job!=\"wireless_router\"}[30s])*8"
    }
   ]
  },
  {
   "title": "NTP offset (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_ntp_offset_seconds" },
    {}
   ]
  },
  {
   "title": "node_network_receive_drop_total (wlan0)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{device=\"wlan0\"}[30s])"
    }
   ]
  },
  {
   "title": "rpi_low_voltage_observed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi_low_voltage_observed", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}