FROM heads-build-armhf

WORKDIR /build

COPY common /build/common
COPY camera /build/camera
COPY cmd/camera ./cmd/camera

RUN mkdir -p bin && go build -o bin ./cmd/camera

ARG TAG
RUN tar -czvf "camera_${TAG}_armhf.tar.gz" bin
