#!/usr/bin/env python3

import glob
import itertools
import os

from packages import Package

DEFAULT_KEEP = 2


def key(p: Package) -> str:
    return f"{p.name}::{p.arch}"


class List:
    pass


def prune(path: str, pkgs: list, num_keep: int):
    pkgs.sort(key=lambda p: p.version, reverse=True)

    keep = pkgs[:num_keep]
    remove = pkgs[num_keep:]

    for p in keep:
        print("ke", p)
    for p in remove:
        print("rm", p)
        os.unlink(os.path.join(p.filename))
    print("")


def main():
    path = "builds"

    filenames = glob.glob(f"{path}/*/*.tar.gz")
    filenames = [f for f in filenames if f.count("_") == 2]

    files = [Package.parse(f) for f in filenames]

    files.sort(key=key)
    grouped = itertools.groupby(files, key=key)

    for k, v in grouped:
        prune(path, list(v), DEFAULT_KEEP)


if __name__ == '__main__':
    main()
