FROM heads-build-arm

COPY common /build/common
COPY timesync /build/timesync

WORKDIR /build/timesync/

RUN CGO_ENABLED=1 go build .

WORKDIR /app

RUN cp /build/timesync/timesync /app

RUN mkdir -p /pkg

WORKDIR /
RUN tar -czvf /pkg/timesync.tar.gz app