FROM golang:1.15-buster@sha256:83b4fd9355ba9ff2d0c78cdf6fc485f739a2834c27e3160a5026faf66f4f5913
FROM golang:1.15-buster

WORKDIR /pkg

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget dpkg-dev

RUN arch=`dpkg-architecture -q DEB_BUILD_ARCH`; \
    wget https://theheads.sfo2.digitaloceanspaces.com/build/opencv_4.4.0-2_${arch}.deb

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ./opencv_4.4.0-2_*.deb
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg

COPY common/go.* /build/common/
COPY boss/go.* /build/boss/
COPY system-tools/go.* /build/system-tools/

WORKDIR /build/common/
RUN go mod download

WORKDIR /build/boss/
RUN go mod download

WORKDIR /build/system-tools/
RUN go mod download
