FROM heads-build-arm64

WORKDIR /app

RUN CGO_ENABLED=1 go get github.com/prometheus/prometheus/cmd/...

RUN cp /go/bin/prom* /app

RUN mkdir -p /pkg

WORKDIR /
RUN tar -czvf "/pkg/prometheus_0.0.0_arm64.tar.gz" app