FROM heads-build-arm64

WORKDIR /build

RUN git clone https://github.com/prometheus/alertmanager.git
RUN cd alertmanager && make build

RUN mkdir app
RUN cp alertmanager/alertmanager app
RUN cp -r alertmanager/web app

RUN tar -czvf "alertmanager_0.0.0_arm64.tar.gz" app