FROM heads-build-arm64

COPY common /build/common
COPY system-tools /build/system-tools

WORKDIR /build/system-tools/

RUN CGO_ENABLED=1 go build .

WORKDIR /app

RUN cp /build/system-tools/system-tools /app

RUN mkdir -p /pkg

WORKDIR /
RUN tar -czvf "/pkg/system-tools_0.0.0_arm64.tar.gz" app