FROM heads-build-common

COPY common /build/common
COPY boss /build/boss

WORKDIR /build/boss/

RUN CGO_ENABLED=1 go build ./cmd/boss

WORKDIR /app

RUN cp /build/boss/boss /build/boss/boss.html /app
COPY --from=boss-ui /install /app/boss-ui/build

RUN mkdir -p /pkg

WORKDIR /
RUN tar -czvf /pkg/boss.tar.gz app