FROM golang:1.15-buster@sha256:83b4fd9355ba9ff2d0c78cdf6fc485f739a2834c27e3160a5026faf66f4f5913

WORKDIR /pkg

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget dpkg-dev

COPY common/go.* /build/common/
COPY boss/go.* /build/boss/
COPY system-tools/go.* /build/system-tools/

WORKDIR /build/common/
RUN go mod download

WORKDIR /build/boss/
RUN go mod download

WORKDIR /build/system-tools/
RUN go mod download
