FROM heads-build-common

COPY common /build/common
COPY head /build/head

WORKDIR /build/head/

RUN CGO_ENABLED=1 go build ./cmd/head

WORKDIR /app

RUN cp /build/head/head /app

RUN mkdir -p /pkg

WORKDIR /
RUN tar -czvf /pkg/head.tar.gz app