FROM heads-build-arm

WORKDIR /build

COPY common /build/common
COPY camera /build/camera

RUN cd camera && CGO_ENABLED=1 go build ./cmd/camera

RUN mkdir app
RUN cp camera/camera camera/index.html app
RUN cp -r camera/js app

RUN tar -czvf "camera_0.0.0_armhf.tar.gz" app

