FROM heads-build-arm64

WORKDIR /build

COPY rtunneld ./rtunneld

RUN cd rtunneld && CGO_ENABLED=1 go build .

RUN mkdir app
RUN cp rtunneld/rtunneld app
RUN tar -czvf "rtunneld_0.0.0_arm64.tar.gz" app